apiVersion: v1
kind: Pod

metadata:
  name: impossible-pod
  namespace: devops-class

spec:
  containers:
    - name: nginx
      image: nginx:alpine

      resources:
        requests:
          cpu: "100"
          memory: "64Mi"


