apiVersion: v1
kind: Service

metadata:
  name: student-api-service
  namespace: devops-class

spec:
  type: ClusterIP

  selector:
    app: student-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
